<?php

namespace Ivey\Callmeback\Block;

use Magento\Customer\Model\Session;
use Magento\Framework\View\Element\Template;

class Popup extends Template
{
    protected $_template = 'Ivey_Callmeback::popup.phtml';

    protected $customerSession;

    public function __construct(Template\Context $context, Session $customerSession, array $data = [])
    {
        $this->customerSession = $customerSession;
        parent::__construct($context, $data);
    }

    /**
     * Returns phone number for the logged in user
     * @return string
     */
    public function getUserPhoneNumber()
    {
        if ($this->customerSession->isLoggedIn()) {
            return $this->customerSession->getCustomer()->getPrimaryBillingAddress()->getTelephone();
        }
        return '';
    }

    public function getJsLayout()
    {
        return parent::getJsLayout(); // TODO: Change the autogenerated stub
    }
}